DSLXREF=../../cvstools/dslxref

all:

XREF: db31.dsl dbadmon.dsl dbautoc.dsl dbbibl.dsl dbblock.dsl \
      dbcallou.dsl dbchunk.dsl dbcompon.dsl dbdivis.dsl \
      dbefsyn.dsl dbfootn.dsl dbgloss.dsl dbgraph.dsl dbhtml.dsl \
      dbindex.dsl dbinfo.dsl dbinline.dsl dblink.dsl dblists.dsl \
      dblot.dsl dbmath.dsl dbmsgset.dsl dbnavig.dsl dbparam.dsl \
      dbpi.dsl dbprocdr.dsl dbrfntry.dsl dbsect.dsl dbsynop.dsl \
      dbtable.dsl dbtitle.dsl dbttlpg.dsl dbverb.dsl docbook.dsl \
      version.dsl
	$(DSLXREF) docbook.dsl > XREF

clean:
	rm -f XREF

