#!/bin/bash -e

. /usr/share/debconf/confmodule

db_version 2.0
db_capb backup

db_title "Modular DocBook DSSSL Stylesheets"

# we don't care to group these, and all have the same priority
questions=(show-comments set-papersize html-ext use-id-as-filename \
           body-start-indent visual-acuity title-font-family)
priorities=(low medium low low \
            low low low)
upbound=$((${#questions[*]}))

STATE=0
while [ "$STATE" != -1 -a "$STATE" != $upbound ]; do
    db_input ${priorities[$STATE]:-medium} docbook-dsssl/${questions[$STATE]} || true
	
    if db_go; then
	STATE=$(($STATE + 1))
    else
	STATE=$(($STATE - 1))
    fi
done
