#!/bin/sh

PACKAGE=docbook-dsssl
CENTRALCAT=/etc/sgml/${PACKAGE}.cat

set -e

if [ "$1" = purge ]; then
    rm -f ${CENTRALCAT} ${CENTRALCAT}.old
    rm -rf /etc/sgml/${PACKAGE}
fi

#DEBHELPER#

exit 0
