#!/bin/sh

set -e

case "$1" in
    remove)
        rm -f /var/www/docbook-dsssl || true
        ;;
    abort-install)
        # Back out of an attempt to install this package.  Undo the effects of
        # "preinst install...".
        rm -f /var/www/docbook-dsssl || true
        ;;
esac

#DEBHELPER#

exit 0
