#!/bin/sh

set -e

if [ "$1" = install ]; then

    # create the symlink to /var/www/docbook-dsssl we do it here in
    # the preinst so that if it is removed by the sysadmin, it is not
    # recreated when the package is upgraded

    if [ -d /var/www -a ! -e /var/www/docbook-dsssl ]; then
        ln -sf /usr/share/sgml/docbook/stylesheet/dsssl/modular/images /var/www/docbook-dsssl
    fi
fi

#DEBHELPER#

exit 0


